# Generated by Django 6.0.7 on 2026-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='SUCCESS', max_length=10)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online'), ('POINTS', 'Points')], default='CARD', max_length=10)),
                ('type', models.CharField(choices=[('REFUND', 'Refund'), ('PAYMENT', 'Payment')], default='PAYMENT', max_length=10)),
                ('trans_id', models.CharField(blank=True, max_length=255, null=True)),
                ('order_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('card_number', models.CharField(blank=True, max_length=50, null=True)),
                ('job_change_id', models.IntegerField(blank=True, null=True)),
                ('transactions_history', models.JSONField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True)),
                ('payment_id', models.IntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('card_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(max_length=255)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_pendingrefund',
                'ordering': ['-created_at'],
            },
        ),
    ]
