# Generated by Django 6.0.7 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_car_options_remove_car_owner_car_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='owner_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
