# Generated by Django 6.0.7 on 2026-07-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('coupon_on', models.CharField(choices=[('product', 'Product'), ('shipping', 'Shipping'), ('combined', 'Combined')], max_length=50)),
                ('coupon_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], max_length=50)),
                ('coupon_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('coupon_start_date', models.DateTimeField()),
                ('coupon_expiry_date', models.DateTimeField()),
                ('limit_per_user', models.IntegerField(default=-1)),
                ('limit_per_coupon', models.IntegerField(default=-1)),
                ('coupon_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'promotion_coupon',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_products', to='promotion.coupon')),
            ],
            options={
                'db_table': 'promotion_couponproduct',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='couponproduct',
            constraint=models.UniqueConstraint(fields=('coupon', 'product_id'), name='unique_coupon_product'),
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('order_id', models.IntegerField(db_index=True, unique=True)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CONFIRMED', 'Confirmed'), ('REVERSED', 'Reversed')], default='RESERVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promotion.coupon')),
            ],
            options={
                'db_table': 'promotion_couponusage',
                'ordering': ['-created_at'],
            },
        ),
    ]
