# Generated by Django 6.0.7 on 2026-07-14 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'catalog_productcategory',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('product_code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_by_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('product_type', models.CharField(default='OFFSET', max_length=255)),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sqr_ft_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shop_rate_per_hr', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=False)),
                ('on_draft', models.BooleanField(default=True)),
                ('base_turnaround', models.IntegerField(default=2)),
                ('combined_shipping', models.BooleanField(default=False)),
                ('ordering', models.IntegerField(default=1)),
                ('show_faq', models.BooleanField(default=True)),
                ('shipping_type', models.CharField(default='DEFAULT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.productcategory')),
            ],
            options={
                'db_table': 'catalog_product',
                'ordering': ['-is_active', '-on_draft', 'ordering', '-created_at'],
            },
        ),
    ]
