# Generated by Django 6.0.7 on 2026-07-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='rolepermission',
            name='assigned_by',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='assigned_by_id',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_id',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='userrole',
            name='assigned_by_id',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user_id', 'role')},
        ),
    ]
