# Generated by Django 6.0.7 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_alter_permission_options_alter_role_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='assigned_by_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='assigned_by_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
