# Generated by Django 6.0.7 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_options_remove_owner_user_owner_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
