# Generated by Django 6.0.7 on 2026-07-13 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_type', models.CharField(choices=[('login-otp', 'login-otp'), ('password-reset-otp', 'password-reset-otp'), ('email-verify-otp', 'email-verify-otp'), ('phone-verify-otp', 'phone-verify-otp')], db_index=True, max_length=32)),
                ('code_hash', models.CharField(max_length=255)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'otp_one_time_password',
                'ordering': ['-created_at'],
            },
        ),
    ]
