# Generated by Django 6.0.7 on 2026-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_alter_onetimepassword_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='user_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
