# Generated by Django 6.0.7 on 2026-07-13 13:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeadLetterEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_class_path', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('error_message', models.TextField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event_dead_letter',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_class_path', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'event outbox entries',
                'db_table': 'event_outbox',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=128)),
                ('event_class_path', models.CharField(db_index=True, max_length=255)),
                ('aggregate_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('payload', models.JSONField()),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'event_store',
                'ordering': ['-published_at'],
            },
        ),
    ]
